spring:
  application:
    name: core-ledger
  datasource:
    url: jdbc:postgresql://localhost:5432/core_ledger
    username: postgres
    password: 123456
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

external-bank-gateway:
  base-url: http://localhost:8081